version: "2"

services:
  database:
    image: mongo:4
    container_name: witmon-database
    ports:
      - $MONGO_PORT:27017
    environment:
      MONGO_DATABASE_USERNAME: $MONGO_DATABASE_USERNAME
      MONGO_DATABASE_PASSWORD: $MONGO_DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongodb_data:/data/db

  api:
    image: witnet/witmon-api
    ports:
      - "4000:4000"
    links:
      - database
    depends_on:
      - database
    environment:
      SERVER_PORT: $SERVER_PORT
      DB_HOSTNAME: $DB_HOSTNAME
      MONGO_PORT: $MONGO_PORT
      MONGO_DATABASE_USERNAME: $MONGO_DATABASE_USERNAME
      MONGO_DATABASE_PASSWORD: $MONGO_DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $ME_CONFIG_BASICAUTH_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $ME_CONFIG_BASICAUTH_PASSWORD